language: node_js
node_js:
  - lts/*

install:
  - pnpm install --frozen-lockfile
script:
  - pnpm build
cache: pnpm install

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master

notifications:
  email:
    - lalifeier@gmail.com
  on_success: change
  on_failure: always
